"""Build the corpus manifest (T0.2).

    .\\.venv\\Scripts\\python.exe scripts\\build_manifest.py

Provenance comes from ``corpus/sources.yaml``; everything countable is measured here
with our own parser rather than typed in by hand. That has a useful side effect: the
manifest cannot be built unless the parser survives every file in the corpus, so this
doubles as a broad parse-coverage check.

Exits non-zero if a required construct has no package, which is the machine-checked
half of the T0.2 gate.
"""

from __future__ import annotations

import hashlib
import re
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from lineage.parsing.plsql import parse_program

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "corpus"
SOURCES = CORPUS / "sources.yaml"
MANIFEST = CORPUS / "manifest.yaml"

# b0_01_insert_select.sql -> insert_select ; s3_shared_temp_table.sql -> shared_temp_table
CONSTRUCT = re.compile(r"^(?:b\d+_\d+|s\d+)_(?P<construct>.+)\.sql$")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _line_counts(source: str) -> tuple[int, int]:
    """Total lines, and lines that are neither blank nor comment-only."""
    total = 0
    code = 0
    for raw in source.splitlines():
        total += 1
        stripped = raw.strip()
        if stripped and not stripped.startswith("--"):
            code += 1
    return total, code


def _collection_of(path: Path) -> str:
    relative = path.relative_to(CORPUS)
    return relative.parent.as_posix()


def measure(path: Path) -> dict[str, Any]:
    """Parse one corpus file and record what it contains."""
    source = path.read_text(encoding="utf-8")
    program = parse_program(source)
    total_lines, code_lines = _line_counts(source)

    match = CONSTRUCT.match(path.name)
    entry: dict[str, Any] = {
        "path": path.relative_to(CORPUS).as_posix(),
        "collection": _collection_of(path),
        "construct": match.group("construct") if match else None,
        "sha256": _sha256(path),
        "lines_total": total_lines,
        "lines_code": code_lines,
        "statements": len(program.statements),
        "units": program.unit_counts() or {},
        "parse_errors": program.error_count,
    }
    if program.error_count:
        # Recorded, not raised. An unparsed file must be visible as unparsed rather
        # than silently contributing nothing.
        entry["parse_error_detail"] = [str(error) for error in program.errors[:5]]
    return entry


def check_coverage(entries: list[dict[str, Any]], required: dict[str, list[str]]) -> list[str]:
    """Verify every required construct is represented. Returns the missing ones."""
    present = {entry["construct"] for entry in entries if entry["construct"]}
    missing = []
    for band, constructs in required.items():
        for construct in constructs:
            if construct not in present:
                missing.append(f"{band}/{construct}")
    return missing


def main() -> None:
    sources = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))

    files = sorted(p for p in CORPUS.rglob("*.sql"))
    if not files:
        raise SystemExit(f"no .sql files found under {CORPUS}")

    entries = [measure(path) for path in files]
    parse_only = set(sources.get("parse_only") or [])
    for entry in entries:
        entry["parse_only"] = entry["path"] in parse_only

    unit_totals: dict[str, int] = {}
    for entry in entries:
        for kind, count in entry["units"].items():
            unit_totals[kind] = unit_totals.get(kind, 0) + count

    missing = check_coverage(entries, sources.get("required_constructs") or {})
    unparsed = [entry["path"] for entry in entries if entry["parse_errors"]]

    manifest = {
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "generated_by": "scripts/build_manifest.py",
        "note": (
            "Counts are measured with lineage.parsing.plsql, not hand-maintained. "
            "Rebuild after changing the corpus; do not edit this file by hand."
        ),
        "collections": sources.get("collections"),
        "ground_truth_package": sources.get("ground_truth_package"),
        "summary": {
            "files": len(entries),
            "lines_total": sum(e["lines_total"] for e in entries),
            "lines_code": sum(e["lines_code"] for e in entries),
            "statements": sum(e["statements"] for e in entries),
            "units": unit_totals,
            "parse_only_files": len(parse_only),
            "files_with_parse_errors": len(unparsed),
            "required_constructs_missing": missing,
        },
        "files": entries,
    }

    MANIFEST.write_text(
        yaml.safe_dump(manifest, sort_keys=False, width=100, allow_unicode=True),
        encoding="utf-8",
    )

    summary = manifest["summary"]
    print(f"wrote {MANIFEST.relative_to(ROOT)}")
    print(f"  files          {summary['files']}")
    print(f"  lines (code)   {summary['lines_total']} ({summary['lines_code']})")
    print(f"  statements     {summary['statements']}")
    print(f"  units          {unit_totals}")
    print(f"  parse errors   {summary['files_with_parse_errors']} file(s)")

    if unparsed:
        print("\nfiles the parser could not read cleanly:")
        for path in unparsed:
            print(f"  {path}")

    if missing:
        print("\nMISSING required constructs:")
        for item in missing:
            print(f"  {item}")
        sys.exit("T0.2 coverage requirement not met")

    print("\nall required constructs represented")


if __name__ == "__main__":
    main()
