-- UNANALYSABLE 1 / the loud-failure register, made executable (T3.1)
--
-- Every construct here is real Oracle that the analyser has no lineage semantics for.
-- The register calls these LOUD failures and that is exactly the point: the parser must
-- refuse each one by name, with a code, and emit no edges for it. A loud failure is
-- survivable - somebody sees the gap and goes and looks. A silent one is not.
--
-- Expected output is a REFUSAL PER CONSTRUCT and ZERO EDGES from the refused lines.
--
-- THE CONTROL IS THE POINT OF THE FILE. u1_control is an ordinary INSERT ... SELECT with
-- nothing unusual in it. Its edges must still appear. A classifier that refuses the FILE
-- rather than the STATEMENT would pass every other assertion here and quietly cost recall
-- everywhere else - refusing too much, which looks like discipline and is measured as a
-- false-abstention rate for exactly that reason.
--
-- The control sits at position 7 of 8, AFTER six refusals and BEFORE the wrapped body,
-- and that ordering is a finding rather than a layout choice. A wrapped blob is not valid
-- PL/SQL, so the grammar derails on it and every unit after it is lost - which is exactly
-- what a wrapped package does to a real file, and why WRAPPED is refused at the SOURCE
-- level rather than the statement level. With the control after it, this file proved
-- nothing; the six earlier refusals cost it nothing at all.
--
-- PARSE-ONLY. Nothing here is compiled: several of these constructs reference shapes the
-- seed schema does not carry, and the point of the file is what the analyser SAYS about
-- them, not what the database does with them. Every label is source_read.

-- 1. MODEL. Cell rules compute values by inter-row reference, so a column's value is not
--    a projection of anything in the select list.
CREATE OR REPLACE PROCEDURE u1_model_clause IS
BEGIN
    INSERT INTO fct_revenue (cust_id, period_month, net_amount, order_count)
    SELECT cust_id, period_month, net_amount, order_count
      FROM fct_revenue_stage
     MODEL
        PARTITION BY (cust_id)
        DIMENSION BY (period_month)
        MEASURES (net_amount, order_count)
        RULES (
            net_amount[ANY] = net_amount[CV(period_month)] * 1.1
        );
END u1_model_clause;
/

-- 2. MATCH_RECOGNIZE. Measures are defined over pattern variables bound to row ranges,
--    and which rows a variable covers is decided at runtime.
CREATE OR REPLACE PROCEDURE u1_match_recognize IS
BEGIN
    INSERT INTO fct_revenue (cust_id, period_month, net_amount, order_count)
    SELECT cust_id, period_month, net_amount, order_count
      FROM stg_orders
     MATCH_RECOGNIZE (
        PARTITION BY cust_id
        ORDER BY order_date
        MEASURES FIRST(a.order_date) AS period_month,
                 SUM(b.gross_amount) AS net_amount,
                 COUNT(*)            AS order_count
        PATTERN (a b+)
        DEFINE b AS b.gross_amount > a.gross_amount
     );
END u1_match_recognize;
/

-- 3. PIVOT with a subquery column list. The output COLUMNS are the DATA in the pivot
--    column, so the statement's shape is not fixed by its text - the strongest form of
--    "not decidable", because the arity itself is unknown.
CREATE OR REPLACE PROCEDURE u1_pivot_subquery IS
BEGIN
    INSERT INTO fct_revenue (cust_id, period_month, net_amount, order_count)
    SELECT *
      FROM (SELECT cust_id, currency, gross_amount FROM stg_orders)
     PIVOT (SUM(gross_amount) FOR currency IN (SELECT currency FROM stg_orders));
END u1_pivot_subquery;
/

-- 4. CONNECT BY. Rows are generated by walking a self-relationship, so a value in the
--    result may have come from any depth and the path is not statically bounded.
CREATE OR REPLACE PROCEDURE u1_hierarchical IS
BEGIN
    INSERT INTO dim_customer_hier (cust_id, parent_cust_id, depth, root_name)
    SELECT cust_id,
           parent_cust_id,
           LEVEL,
           CONNECT_BY_ROOT root_name
      FROM dim_customer_hier
     START WITH parent_cust_id IS NULL
   CONNECT BY PRIOR cust_id = parent_cust_id;
END u1_hierarchical;
/

-- 5. Conditional compilation. Which branch EXISTS in the compiled unit depends on
--    PLSQL_CCFLAGS at compile time, so this source describes several different programs
--    and only the database knows which one was built.
CREATE OR REPLACE PROCEDURE u1_conditional_compilation IS
BEGIN
    $IF $$audit_enabled $THEN
    INSERT INTO dw_audit_log (cust_id, changed_by, changed_at)
    SELECT cust_id, USER, SYSDATE FROM stg_customer;
    $ELSE
    INSERT INTO tmp_recent (cust_id, last_login)
    SELECT cust_id, last_login FROM stg_customer;
    $END
    NULL;
END u1_conditional_compilation;
/

-- 6. XMLTABLE. Columns are projected out of a document by path expression, and the
--    document's structure is nowhere in the dictionary.
CREATE OR REPLACE PROCEDURE u1_xmltable IS
BEGIN
    INSERT INTO tmp_recent (cust_id, last_login)
    SELECT x.cust_id, x.last_login
      FROM stg_customer s,
           XMLTABLE('/customer'
                    PASSING s.payload
                    COLUMNS cust_id    NUMBER PATH 'id',
                            last_login DATE   PATH 'login') x;
END u1_xmltable;
/

-- THE CONTROL. Nothing unusual. These edges must survive every refusal above.
CREATE OR REPLACE PROCEDURE u1_control IS
BEGIN
    DBMS_APPLICATION_INFO.SET_MODULE('LINEAGE_CORPUS', 'u1_control');

    INSERT INTO tmp_recent (cust_id, last_login)
    SELECT cust_id, last_login
      FROM stg_customer
     WHERE last_login > SYSDATE - 30;

    COMMIT;
END u1_control;
/

-- 7. Wrapped PL/SQL. The body is stored obfuscated; there is no source to read, and no
--    amount of parser work changes that. Only runtime evidence can say what it touches.
CREATE OR REPLACE PROCEDURE u1_wrapped WRAPPED
a000000
369
abcd
abcd
7
c2 45 5a
kJ4TCwjZ8Xk9nvMg1PqRr7dLYbAwg5nnm7+fMr8fVQ==
/
